# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""



seq = "CTAAGATATGCTAGCGGCCGTTTTAGAAATGCATTCCAATATTTTGAACGCCGAAATAGCGCAGGTCGCCCAATATAACCTAGCTGTCATGACAGTATTAGCGCTTTTTTGCGAGTGGGTGTCTCTAGGCTCGTTACAGTAATCGGTCGATCATTTTTAATTTTGTGCAGGCAAGGCACGGGCTGGTTTTGCAGACATGCCTAAACCCACCGGCCATATAGATCTATCACGACACATCAGAGGGTGGATGTGATTTAGGATAGGATGCACTTCTCGCACCGTTCTCAACGGATTAGTACTGTGGGCCGTAAAGTGTCAGCTGTCTCAATCAATACGATCTCGAGCGATGTCGGTTGTAGTAGGCAGCGAAAGCTGGTTTCATTGTAGTAATTGTCCTTTCTCTGTTGTCACCGATGCGTACTACTGCTTCATTCCCGAAGAGCCGTCCGGGTGAGATTCGTGAATCCTTGTGTTTCGACTTACCTATTTAAGCCCTGCGCTTACACACCTTCAAATGGATTATCATGGTCCTTCAGCACGAAGACGGAGCCGTGTGCAGCTCAGGCTCCACCGAGCGATTATAAAATCTCTGGTTTCGTCGACGGGTAGGTCAAACATGGCTGTGCCGTAATGCAGCTTCTAAGTCTAGAGTTACTGTGCGATTTACCGTCTAGGAACGATCTACGCACCTTTAGAAGTCGATTCTTGCGCATCCTAAAGACATTACGAGGAGAGATAGGATAGTGGTCGAGCCGCTATGTCATTAGCCGGCTGTGCCGGGGAGGACGCCTCATGGTACTTGGGAGGCAGCCGGGGATGGTCCTTTGGTCTCGGCCCGCTTCCCGAAATAAACTCACCTGTGGACATCTGCCTAGATCACGGCCAATAAAGTGTCTCCAC"


def dna2rna(dna):
    
    l= list(dna)    
    rna=list()
    for i in l:
        if i == "T":
            rna.append("U")
        else:
            rna.append(i)
    
    return rna
        
    

def list2string(l):
    
    str1=""
    for el in l:
        str1=str1+el
        
    return str1
    
r = dna2rna(seq)

sol = list2string(r)       

print(sol)

