# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

from collections import deque

seq = "TTACCTTAACAAACGAAAGTCGCCTGAGTCTACAGGATCTCCACTGACATGGCATCGTGGACGGATACTCATTGTCGGGGTTACAAGCGCCTATTCAAGCCCACAGCGGAAGCCTAAGGGATTGAAGAGCTTGACAAGAATACATGCAGTGAGATCAGTCGGTAGAGACAGACGCAGGATTAAGTTTAATTAGCGCGCAAAATCAGCCTGTGATTTCGATAGCTAAGGCACCCCTGCTGAACTGAACGCCAATGGTTAACGCCTGTAAGACTCGTTCTCCTGCCGAGGACTTGCCTTATGCGCTCGAAGCCCTATCCTGAGGATTTCCGCATCACGTGGTCTAGAAGTAGCAGTGGTACGCTATGGAGCTGTAAACAGACAATCTTCCGTCGACACCCTACCTATCACGCTTAGGATACCACATGTCTCGCGAGTAACACTAGAGCGATTATAATAAAAGTCACCGCCTTCCGAAATCTATCCGTCTCGTCGGCTTCTAAATCGACGTCGTTGCGCGTTCGAGCCCAAAATAGCAGGGTTGGAACCAAAAACAGTTGAGATCGTTTTACCACTAGCGAAGAAACCGGGCTGAAGTTCACCTGGTGCAGCACATAAAGCCTTGTGCACACCCTAGTATCTTGGCCAGCAAGCGAACCTAACGTTGACGATACGGCCTCATGGACGGATTCGGGCGCGTCTTATAGTCACAGCGAAGTAAAGGACAGCGATGCGTGAAAGAAGTCTTCGAAATTCCTTCGAAGTTCCGGACCTCGGTAGATTCCGCCCAGGCAGTCAACGATGAG"

def dna2rev(dna):
    
    l= list(dna) 
    
    rev=deque()
    for i in l:
        if i == "T":
            rev.appendleft("A")
        elif i == "A":
            rev.appendleft("T")
        elif i == "C":
            rev.appendleft("G")
        elif i == "G":
            rev.appendleft("C")
    
    return rev
        
    

def list2string(l):
    
    str1=""
    for el in l:
        str1=str1+el
        
    return str1
    
r = dna2rev(seq)

sol = list2string(r)       

print(sol)

