#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb  1 17:16:44 2020

@author: matteobellini
"""

solution = ""

s = "GGTCACTGGTCACTAGGTCACTGATAGGTCACTAGGTCACTGGTCACTGGTCACTTAGATCGGTCACTAAGAATTGGCGAGGGAGGGTCACTGGTCACTGGTCACTCTGGTCACTGAGGGTCACTTCAGGTCACTAAAAGGTCACTAGGTCACTAGGGTCACTATTGGTCACTGGTCACTGAATAGATCGGTCACTTACCTGGTCACTAGGTCACTCGGGTCACTCGGTCACTAGGTCACTAGGTCACTCCGTAGGTCACTGCGGTCACTCCGGTCACTGGTCACTCGGTCACTGGTCACTATGGTCACTCCGCCTCGACAAGGTCACTAAGCGTTTGGTCACTGGTCACTGGTCACTGGTCACTTGGTCACTTCGGTCACTGGTCACTGGTCACTGCGGTCACTAAGGGTCACTACTAGGTCACTGGTCACTGGTCACTTTCCTGGCTGGTCACTGGTCACTTCTGGTCACTGGTCACTTGGTCACTGGTCACTGGTCACTCGTGGTCACTGGTCACTGGTCACTCTGGTCACTGGTCACTCTTTTCGTGAACTAGGTCACTAGCTTATAACTGAGCGGTCACTGGTCACTGGTCACTAAGGTCACTGGTCACTGTTGGTCACTGGTCACTTGAGGTCACTTGAAAGGTCACTTGGTCACTTGGTCACTGGTCACTTGGGTCACTGGTCACTTCAAAGGTCACTGGTGGCGGTCACTTTCGGTCACTAGAGGTCACTAGGTCACTATGGTCACTGGTCACTTGGTCACTGGGTCACTACCCGGTCACTGGTCACTAATAGGA"
 
t = "GGTCACTGG"

res = ([i for i in range(len(s)) if s.startswith(t, i)])


for num in res:
    
    n = int(num) + 1
    
    solution = solution + str(n) + " "
    
print(solution)