# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""



from textwrap import wrap

outfile = ""


infile = "AUGCACUAUAUACGAUCCCCUCCGUCGCGUCGGCUCUCUUUCAGUCCCGAGAUUGAUUGUGGAGUAGACGCAAAUGGGGGUCAUUUUCACAUGGGCUAUAAGGGUACAACGAUCUUGCUUACGAAACACGGAACAGAAAUCGACCGUUCCUUGGAACACCUUUUAUUGGUAGCCCGCAAGAUACCAGCACAUAUCUCGCGAUCCAAGUAUUUCGAUCCGCGUCUCAGUUGGUAUCGCAACGGGGGGCGUUAUGCUGUAACGAACGACCCAGGUAUCAAUAUUAUCGUGCGCUGUGGACCACCGAAACGUCCCGGUCUACCUAUCAAGGGUCUGGAGUUUCAAUCGAAGUACUGUCACGUAGAGUGUGCCGGGUGCGUAGCGUACCAAGCCGCUGGACGUUGUUGGACGGAUUCCACACUUAGUCCACGCGAGGGGGUAAAAUACAGUUCCGCCGCCUACGCAACUGGUAAACAUAUUGUCCGCGCGGUUCGGCUAUCUUCCACCGAUGUUAACAGGAAGAUCUUUUACCAGACCCCUCUUUCCUUGAACCUAAUCAACGUCUUACAGCAGUUGUACAGUUUAUAUACGAGGACGGGCGGGCCUAAAAAGAGAGACUCUCCUGAUGAACGUUUCAAUUUCUCAAAAAAUGACUGUUCGACCAAAUGGCCUAAAGGACCAAGUACGGCCCCAAUGGUUUUGCACGUUGGCGGAAAGUUCAGCCAGCUAGUCGGAUGGACAUCCAAUCCCGCGACAGUCGGCGUGGGUAUCCCAGACCCCGUUUCCCCAGCCAUUCGUGCAGUAGUUGCUGUGCGUCAUGUCCCGUCCGGUGACCGCUACAUAGGGAAUUAUGCGCUCGGGAGGAAGAUUUUCUGGCGCGGGCGUUUGUCGGCCUCCAAGGAAGUACAUUAUGAAAAUCCGCCCAUAAGUCCGAGGCCCGGCAUUUGCGCCGAAGUUAAAUUGACGAAUCACACUCGUUCACAGAGAACGCACCGACAAAUUGGUACAGUCAUUGAGACACACGCUAUUCCCGGACCAAUCGAGGCAUAUAGGGCGGCUCCAUACACCCUUCAAACCACUGUUUACUAUUGGUCAACAAAGGCCGACGCUAACUUCCCCAUGCAUGUGUAUUUGCGUGCUAUAGAAAAUAAGCUAAGGCCAAGCGCCACCGAAAGUAUUCUUCGCCCUUACUUUUUACUAGUGGCAUUUUCUAUAUCGUACUGUGAGGCUGUCGCCCUGUACCGCGGAACAAAACGCCGAUCCGUGGGAUUGGGGCGCUCAGUAUAUAUUAGCCACUUCCUGAGAUGCGCGAGGGCGUGGAUUUUAAAGAAUCCAUUAACGGAGCCUGGCUUUAUGAAUUGCCACUACGUUAGGCUUCCGGUCGCGCGUCUUGGGACGAGCACAAGAACCGGUUGGGGAACGCAGAACAACCAUCUUCUUGCAGCGGGGGGCAUACUCCGUCAUGAGGGACUAAAUUAUGCUACGGGUGUUUGGUAUGGCGAACGUACUUAUCGCAUAACCCGCCUGGGGAUUAUCCGAGACCGUACGAUGGAGGAGCAGAGACUACCCGUUCAAAACGUGCACCCUCGGAAAACCCUCAGGUGCCCCGCCAACAUCACCAAUGUGCAUAUGACUUGUUCUGCUUGGAUCCCACUCUUGCGCAAUUCGCGCAAACUUCCACGAGGCGGACUAGGGUCAUUCAUUAAAUUGGGGCCAGGUCCAGGAACGUACAAGAAGAUUCCUCCAUUGGCGACUCGAAGACUGCACUUAACAACGGGUCCGUGGGGGCUAUCUUUUUGCAGGCGCCACUUGCCCUGGACUGAAGAUCUUAAACUCAAAGUAUCUAGAGCCCGAAACAAGUCCGGACGAUUUAUCUGGCAUGAGAUGAUCAUCGCAAGCGUGACGAGGAUGAUAAACAGGACGGGUACCCAGGGUAACAGAUUCUUCUCGCGCAAGGUAGGCUGCAGCCGGGUUCGUACGUUGUGUAUAUCAUAUAAGAUGCAAUACUCUUCGCUUUUUGGACGUGGUUCCUCGCUGGGGCGCGAAUCCAGAUACCUGGAAUUACAUCGCUGUUCGGUAUAUAUAGGCUUGAGAAUGGAUCACGGCAAUUCGCAUCUAAGGGAAGGCCGACAGAAGUCGCCACAUUUCUCCCAGAGACUAACUAAGUCCCAAGGCGAUUUGUUGGUUUCCCUAUCCUUGUCGGCCAUGACCAACACUCCUACGGAGCGGCGCAGCUCCUGCCCGGUGACUUUGGUGUCUCUACCCUGGGAGGGGUUGCGAUCCUGGUGUGGGGGACUCAGUGCUAAUGGGUACAAUAGUAAAAUUACACCUAUAAUGGAUUUGUUUAGGUACCUUCCAAAUUCUUCCUCUACUUGUGGAUGGAUACCUCAGAGACCAAAUCAUUCUGUCAUGCGCGAGAAAGAUGGGGAUUGUCUCUUUUGGUUGAAACGUCACUCAUGCCCGGGGAUCAGUACAUAUGAGAGCGUCAGACAACUUCCAUAUACGGGAACUUGCGAUAACCGAUGCUUCCAAGGAGUAAGGAACGAAUGCCGAGAUGUAAACUCCUUGAGUAAACUAGAGCGGUUUGCCUGUGGCGUAUGUACACGACGGGCCGAGGAGCGGCGGACUCGCGGCAAGAGUCCGAAACGAAGCAUGCAAGUAUUGGCGUCAUGUCCUAACGCUACCAAAAUUGCGUGUGAUCAAGGGAGAUCAUGCAGCUGGGAAGUGGUAACUCUGGUCUUCCCCACCUGCUUUCCGAUAAAAUUUGUGCCCUUUGUUCCAGUCUUAUACAGUAGCUUUGAAGACCCUCGUGGCCUGAGAAAUGCUACCUUGAUUAGCAUCCUCCUCCACUCUAAAGCGUGCAGGCGUGGGCAUCCAGCUUGCACGAAUCAUGAGGAAGCAGAAACACCGACAACCCAACUGGAGCACAGGGCCGAACACUCGAUUGCUUCGCAUUCAAGCCAUCGUUCAGAGCCAUUUAGCAACCCUUUAGAACGCCGCAGUGUCUGUAGUGCGCCAAAUUCUAAUCACUCAGCGCCGCCCCUCCCCUCAAGGAGGGCUCUCACACGUAAAGGAGCGGUUCAUUCAGAUUUUGGGGAGCGUCCGAGUCUUGUGUGCUCCAAUUGCGCCGUCGAGGGCGGGCUUAUGCUUAACUUUCCCAUCAAGCGGGAACCACGGCGGGUUAAGGGUUGGUCCGUACUCGGAUUGACUCAGGUUGUCCUUGUAUCCGCUACUAACAUACAUCUUCAAUUAGCCCUGGUUGGGGAUACGUCUGCGCCGGGAAGCGAUACUAAGCAUGCGGAAUACACAAGAGGAGUCAGACUGCCUGAGCUGGUGGUUAUUGUGCACGUAUACCCUCCUGGCGGUCCCUCACAUGGGGCGCGCCCAUACUUAGGGCUGGAACUGGACUGGCAUAACGGUAGGGUCUUGUGUAAAUCCAGUGAUUCACUGUCUGGAUGUUCGUGUACCUUCUGUUGCCUAGAUUGCACACAACAAACCUACAAUUGUGAACAAGGCGAGGACACUUCUCCGACCGUAACAGGGGUAGCCCGGGAUUCUCGUUGCUUAAAAUUAAAGCGGAUCAUAUUCCCACUUGCCUACAAUAUGCGGAUGUGGAUCGACUGCUUAAGUAUCACGGCCUGUUGUUUAUCAACAAUUGAGGAACUUGCUGAGUGCUUCGCCAUAUUGUAUCCUGGUGAUCGCGUUCCCGGGAGAAGUCAGUGUGCAACUCUUUAUUACUCCGACAUUAUACAUAAGUGUUUUGGCCGGUCGACCUUAAUCGGGGAUGCAAACUUGGAUGCAGUCGAGGUGCGGGCGUGCACGUCGCUUGCAUUGUUCAUAAAUCCAUACUUGUCACUUGGUGCGAAGACGCAUGGAGCUCUCCACUCGCCAGGAGACAGUGAGGAACACGACCUUGCUCUAAGUCCGUCACUUUUCACCGUUCGUAUGGACGAUGGGCAAGAAAGACUACGUUGCCAUCAUAUCCUCUCAUCCGAUGGACGGCAAAGUCCGAUACGCCUAGUACCUUCUUGUAGGGAGUUUCUCACAGGUGUGGCGAUAUACCUGUCUUAUAUGCAGCCCAUGCUCCGGUACAAAAACAACUGGCACUACUCGUACUCAGCAGCCAUGGAAAUAAGAUGCGGCGACUGUGUUGUGUACUGGGCCAAGCACCGAGUAAUAUUGUUGACACUCUCAGUUAUAUUAGGUACGUUCCGCUGUUGUAGAAUGGUUAGUCCGGGUAGCAUUUCACUCGGACCUCCUCUACAACGAACCCGAACUCGAUCCAGAUCAUAUCGCUGGGGGAAGUCCCCCCUGAGACAAGGUAAGAGUUCCCACGUAUUCCGCGUAAACUUCCAUAGAAAACUUAGCGAAAUGUAUGUCCGCUCAAAGUCUCCCAAUAGCUUUGGCGCAGAUCGACGCGCCUCAUUCCCAAAGGGGUGGGGCCUGAAAAUUCACAAUAGGCACCUUACCAUACCCCACUGGGAUGGUAGCGGUGUAGGGCCAAAUCAUAAUGGGGGUCAUUGGGAGUUUAUCAAGCCAUUACUAGUUCCACAAACGCACUGGUUCUCGACUAGACUUCACGCCCUAUCCAGCACCGGCGGUAAGCCUAACCGUACAGUACCAUCCUUACAUUGGGAACCCUCUUUGGCUUCCGCGCGUGACAGUUUACGGAUCCUCAUAUCACUUCAGUGCCUAUGUACGGUUUGCCUCCUUCCACCUGUUACAUCGGCGUUUUACAUUGUGUCCCUAAUAAAGAGUUCCCGACUUAUGAUAAGGGCCUCGCGACGUGGACCAUGGCGAGCCGGUGCUGUACGUGCUAUUAUGAAGAGAGGGAACGUCCGUCCGGCGCUAAAGGGUACGUGUUCCAGAGAUUAUAUCCUCUCCACCGCGUGCGUUCUUCCGAGCAGGAUCGGCCAACGAAAAGUGUCAACGAAACUAAUUUCAUUUCGAUAUACUGUGCUCAGUUGCCCCAGGAUGUCGGCGAAUAAUCCAUUACCGUUAUGCGACAGGGCGUCCAUGUGGAAAAUAGCAGCGGGCCGCAUGUUCUUCUCACGGCGAUAUCCAUCCAUCCAACUUGCCGCGUUCGCGCGUUGGCCUGUGUUCUAUGAAAUAUACCUUCGAGAUCUAAGCCGAGUCGACUCGAAUUAUCGGUUGACCUUGACGAUUCAUUCAUUGCACCAGUUGAGCUACAAAACAGCGUUGAUACGCAAGUUCCCGGGACAAAUAUCGGCCGGCAGAUGUGAUAGGUCGGAGCCGCGAAGAAAAUUCCUAUGUCGAUAUAAGCACAUCGCCAAGGCGUCGCGCUGCGUAAUGGAUGAUACCCGUAUACAGGAACGGGAUCUCCCUUCGGCAGACAUUCUGAGUACAUUGGCUUUGCCGCAUGGCAGAGAACGAUUCGUAACUGUCCCGGGUCAGGACCGAUUUGUAGUAGUUCGCGGCGCAGUGAAAUCGGCGUCCUCUGUGCUCUACCUUGCCGACUAUCGCAUUCCAAGUGCGGGAGCUGUUGAGAAUCAGGUUCGAUUUAGUACUAGAAAUUAUGCCUCACCACGGACUCCUCGUUGUAUGCAUAGAGAUUAUAGCAUUGUGUCCAUUACGGCGCUUAGUGCCGAUGGUAUGUGUAGUACGGAUAUUCACUCACGUUUCUCAGCUUCGCACUGCACGCUUUGGGUUGGUCGCAGUCUAUCUUUUCCAACUAUUCAUCAUCUCCUAUUAGGUAAUUAUCCCCCGAACGUUUCGUCCAAUUCUUCCAUGUCCGCCCACCUGAUGGUGUGUGAUGGUUUCAUGGCGGAGAGGCUGUAUUACAGGCUCGGAAUGUCGAAACAUUCGGUCGGCAAGAUACUAUGGACUGAGACAAUACGGUACAGGCUUUUACUUAAAAUUCAUAUGUCCAUUAUCGCAUGCGGGCUGCUCGGGCACCUCCAGAACGUUGUUAGGGCUCGUGGCGGGACUCUCUCCGUGAAGCAAACCCUAGUUUUAAAGGCCUAUACCUAUCCUGGCAGCAUACUUACCCAUUAUGGGGGAUCUUACACGUCAACACCCGCGGUUAGGCCCUCAAAAAUAGAGAUUUGGGCUUUAAAGCCAAGAAGAAAAAAUCGAAUAUCCCGGGCUAGGGUAGACAACUAUCAACAUAGUAGAUUAAACUGGUCAUGGUGCACUGUACUGAGUCGCAGUAUACUGGUGUGUUGCUCUACGGUGCAUCAGCACGCGCCGACCCACUGCUCAGCGAUUGGUGCUUCCUGGGUAGCGCUAGAGUAUAGACUAAUUAUAUUAUCAAGACAAACUUCAACCUUGUUUACUGUACUAACUUUAAAUUGCUUACUUUUUCAACUUCGUAGAGAGCUUGCAUGGAGUCUUAUGGACCGGUGCAAUUCUAAAGCAAUACAGCUUAACCAUUUGUACCUAACACAGUCCUUGAUGUCAUCGGAAUCUGACCCGAGAUUAUGUCUUGAUCUCCAUCAAAAAGGGAACCGAAGAUAUGCCCUCGGAGUCCAUCAUUUUUACUCCUGCGGCGUGAGAUUUGCUUACAAUGCAUCUUACUGCAAGCCUUGUAAGACCAUAUACGAAAGUUACGAGUUAAUUUCUGGGCAGAACCACAGAAGCCCCGUUACGGUGUAUCCAACGACUCACUCGGAGACGUUGUCGUACGACCUUGAAGGUUAUAGGUCAGAAGGAUUAUCGAGAGAUACUCAUGUCACAUUCUCGCGGAAUUCCAUUCCCAAGUUUACAAUUACACCUAUACCUGCCCAACCGCGGGUCCUAACGCUGCAGGCGAUUUUAUGGUGUCGCACAAUGACGGCUCGGCUCCCGCCACAUUCUAUGUCCAGAGAGAAACAGAAGAGUGAUUGCUUAUCGCUUAUUUUGAUUAAGGGAAGCCUUCCUCGAAGCUGGUCCAAUGAAACAUUCAGCAGUGGUCCGCCCGGUGAUCCGGCAGAAGCCCGAACACAGGGAUCCCACACCAUUGGUUUUUCCCUAUACUGGACCAGCAGACGUCGUUUGAACAUACGCUUGGCAAGUAAGCGAAACCUGGAAAGGGACGGCCCUUCCUGCCGGUUAUGUGCGAAAAGACUUCGGCGUGACCCUAACGGACAUAAUGAUCAAUCUGUGCCAGCGUCGACGUUGACAAAGAUCGCAUCGCUAGUGGAGGCUCUAACGCGAGGAACCACCCCCUGCAACAUCCCAAAAUCAGGGCGAUUUCCACAUUGUACAUAUGGUGCUGAAGUCAGUAAUUCGUGUUCCGUGAAUCGGUCUUGCGCCUCGUCAAAAUUUCGAGGAAAUCAAACGUCUCAUUCGGUGAGAGGGCACUCCAAUGAAAAGCAUCGCGAACCUGGGAUACUUGAGACAGAAGAGCAGACGCCGGGUCACUCCCGGAUCCUAGAACCUGACCAUCUGCUCCGCUGCCCGCAUCGGAUUACUGCAAUCUUGACGCAGGAUCUGCCGGGCAAGUCCUAUCGCAGAGGUUCUAAGAUUACGAAGGGGCAAGUUUGCCAAGGGUGCGCUCCUCACGCACAGGGCGAAAUUAGGUUAGCGAUGUACUGGCAAGACAAGUCCGACAAAGUCGGGGCUACGGUGCAAUAUAGAAGAUACAAGUGUAACGGACAUGUAUUUACCACAACCAAGAAUUGUUUUUCCUGCAAUCAAGGAAGCAUCGAAGUUAGGUGCUUGGGUUUAGGUAAGUUGGUCUCACACAAGCGGCCCAGCUGUCCAAACACGCGCUUGUUGGAAACCAGGUUCUCUACUGAUAAGUGUGCAAGUCCGUACCUUCGGACAAAUGCAUCAGAUUACCCGCCUGAAAGCCCUUAUAUAAGCUUGUCGUCAUCUGGCCGAGUCGUUCCUCUUAGUAGAUUAAUUUGUGAUCCUAACCCCCGUAUAAGAAGGAGCAAGUUGCCCUACCACAACAUGCCCCGGUCGAUUCGGCCCAAUCACGAUGCGCCUCCUUCCGGCCUACCGAGCGGUGUAUGCUGUGGCGUAAGGUGCAUUCCAUGCAUUACACGAUCAGACACUUUUUGCGAUCGGUACUCGGAGCAUCGCUGUGGAGCAGCAUUGCGGACGGCUUAUGCUCCCACCUACAAGUUUAGCUUGUUAUGCGAAAAGACAAGAGCUCGCGACUCCAGGACUCACACAUGUGUAGCGUCCACGUGCCUCCGAUCGUCGACCGAAGCAAUAUCUCCGGUUGUCGAUCUCCAAACGAAGCGGUCUUGCCUCUUUGUCCACAUGCUUGGGCUGGUCGCCAGAAUUCAGUGCAACAAUGCUUGUUGUACCGAGGACGCUAUUCUCUUAGCCUGCUUGGGAACCAAAGUGGAGGGCCAGAUUAGGCACGUAAAUACAAGGAUGUCAGCGGUAGGACGCCAGAGGAUACGCUCUGCAGCAACAGGGAUGGGAUUGAUGAAAGCAAAAGCGCUAUUUGCGGUACACGAUCUUCUGCUGGAGGCCUGUGCCGACAGGGCUUCUGAUAACCGUGGGGGGGUAGAACAAGCUACUUACAUCGAUAGCCCAAGUACGGGUAGCCACUUUAGCAGUCGAUAUCGGAUGCCCGGUAGAGCGAAGACAGUUCGCUCCGUGGUGAAGAUCUCUGGUAUUGUUCCCAUCAAGGCGAUUCAGAAGCGAUCACCCCAGCCCAUCGCGGUUCGCGCGGGAGCCAUGGACAUAGUUGAUAGAAGGUCAGUCUACCGCCAAGGGGGCCCCAAAGCUACCCCGCGUGUGAGGCCGCGGUACCCCGGCUUUAAAAGUCGCCCACUAGUCUCGGCAAUGGGUGUUGUCAAUUUCAUCACCAUUUUUUGUUGCGUACCUCACGUAAAAAUCCGCCGAGACUCUGUAACGGCAGAUUUUGACUCCCGCCAAGUAGUUAAAGCGAACACCCCGUCAUUUCGUAAACACUACGGGACAUUGGGAACCACAUCAGGUGGGUCUUUACCGCGUUGUAGGUUGGACGAUUUCGAAAAGCCGUCGUUAACUAUGUCGCUGGGUACACUGAUUGGUGGACUGGCUUCUCCCGCGUAA"


codon = wrap(infile,3)

for i in codon:
    
    if i == "UUU" or i == "UUC" :
        
        outfile = outfile+"F"
        
    elif i == "UUA" or i == "UUG":
        
        outfile = outfile+"L"
        
    elif i[:-1] == "UC":
        
        outfile = outfile+"S"
        
    elif i == "UAU" or i == "UAC":
        
        outfile = outfile+"Y"
    
    elif i == "UAA" or i == "UAG":
        
        #outfile = outfile+"stop"
        
        break
        
    elif i == "UGU" or i == "UGC":
        
        outfile = outfile+"C"
        
    elif i == "UGA":
        
        #outfile = outfile+"stop"
        
        break
        
    elif i == "UGG":
        
        outfile = outfile+"W"
        
    elif i[:-1] == "CU":
        
        outfile = outfile+"L"
        
   
    elif i[:-1] == "CC":
        
        outfile = outfile+"P"
        
    
    elif i == "CAU" or i == "CAC":
        
        outfile = outfile+"H"
    
    elif i == "CAA" or i == "CAG":
        
        outfile = outfile+"Q"
        
    
    elif i[:-1] == "CG":
        
        outfile = outfile+"R"
        
    elif i == "AUU" or i == "AUC" or i == "AUA":
        
        outfile = outfile+"I"
        
    elif i == "AUG" :
        
        outfile = outfile+"M"
        
    elif i[:-1] == "AC":
        
        outfile = outfile+"T"
        
    elif i == "AAU" or i == "AAC":
        
        outfile = outfile+"N"
        
    elif i == "AAA" or i == "AAG":
        
        outfile = outfile+"K"
        
    elif i == "AGU" or i == "AGC":
        
        outfile = outfile+"S"
        
    elif i == "AGA" or i == "AGG":
        
        outfile = outfile+"R"
    
    elif i[:-1] == "GU":
        
        outfile = outfile+"V"
        
    elif i[:-1] == "GC":
        
        outfile = outfile+"A"
        
    elif i == "GAU" or i == "GAC":
        
        outfile = outfile+"D"
        
    elif i == "GAA" or i == "GAG":
        
        outfile = outfile+"E"
        
    elif i[:-1] == "GG" :
        
        outfile = outfile+"G"

print(outfile) 
    
    
    
    
        

    
    
    





