# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

#f = open("rosalind.txt","r")



def countNucl(f):
    l = list(f)
    numNucl = {'A':0,'C':0,'G':0,'T':0}
    for i in l:
        
        numNucl[i] = numNucl[i]+1
        
    return (numNucl)
    
seq = "GAGAATCGCGGAGCTTGCAGTTGGGGTTAGCCATTATGTTTATCTGGGACGCGTGACGGGGGTCGTGAGGCGTCACCCCATCTGCTACTCCTACGGTTTCCGCAGTTGGCATAGTGTCGCTTTAGTTATGCTTAGACCCTCGCCTTGAGTATGTTTAAACTGCCATTGCGAAGGCCGCGTCCGGCCTTATCTCTCTGACCCGGTTAGGTAGGGACCCCGCGTAGGGCCCATGCCGCTACCAATCATATGCTGAGGGTGGATTGAGTGGATTGCGATCGAAGAGGCCTAACGTGAACGAAGACCCAGGACGTATTATTTACTGGCTTTAGTTATACTACAACCCGGCTTATGGGTGCGAAATCAGGGCCCCCCCGGAGGACTCAATTAACGGGTCACCGATTACATCGAAAGCGCCGGCCCGCCGAATTAAGGCTCTCATAGTCCCCTTCTGGGAAAACACGCTTCAGCTTTCCGTTAGGCGGGCGATTTCATGAGTTCTTCTTGCGATACCGATAATCCAAGGCTGTAACAACGCATGGTCTCATATGGTTGAATTAGAGTTGTCTAGACACGGCCGCTAGGTACGGAATTCGGGCCCCTGAACCCCATCTAAGGACAGTCTACGACATGCTTCAGCCATGAATGGAGAGTTCGACACACTCTCCGGCGCGCTACTGAACTAAATCCACACCCTCGCATCGAGGTTAGCAATGTCCGAGGTATGGGCCCGCGGGACCCCCACAAAAGAGGGGATTCAAGGGGCCGCGCTACCCTTAGGCGATTTTCCTACTCAATCCGACCGTGTTATCCCGGGTTGTACAGCTCAATACTTTTAGGGAAAGGCTCGGCCCGCGAATATAACCTCTTCTCGGTTCTTGTACTGGCGTCCCCATCGTGGACATACGTGACAATATCTGTTCAGGACACACCTCCGCCGCGGCGGCAAGCACTTTAAATATGCTTCGGAAAT"

res = countNucl(seq)

sol = list(res.values())

print(str(sol[0])+" "+str(sol[1])+" "+str(sol[2])+" "+str(sol[3]))